# Generated by Django 3.2.7 on 2021-09-24 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Filter_Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(choices=[('1 TO 50', '1 TO 50'), ('50 TO 100', '50 TO 100'), ('50 TO 100', '50 TO 100'), ('100 TO 200', '100 TO 200'), ('200 TO 300', '200 TO 300'), ('300 TO 400', '300 TO 400'), ('400 TO 500', '400 TO 500'), ('500 TO 600', '500 TO 600'), ('600 TO 700', '600 TO 700'), ('700 TO 800', '700 TO 800'), ('900 TO 1000', '900 TO 1000'), ('', '')], max_length=60)),
            ],
        ),
    ]
