# Generated by Django 3.2.7 on 2021-09-24 02:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Filter_Price',
            new_name='FilterPrice',
        ),
    ]
